spring.application.name=store-api
# S\u1eeda l\u1ea1i URL k\u1ebft n\u1ed1i c\u1ee7a b\u1ea1n gi\u1ed1ng nh\u01b0 th\u1ebf n\u00e0y (nh\u1edb thay mini_notion th\u00e0nh t\u00ean database th\u1ef1c t\u1ebf c\u1ee7a b\u1ea1n)
spring.datasource.url=jdbc:mysql://localhost:3306/local_db?allowPublicKeyRetrieval=true&useSSL=false

spring.datasource.username=root
spring.datasource.password=anhmy1312
# T\u1ef1 \u0111\u1ed9ng c\u1eadp nh\u1eadt c\u1ea5u tr\u00fac b\u1ea3ng d\u01b0\u1edbi Database khi code Java thay \u0111\u1ed5i (Entity)
spring.jpa.hibernate.ddl-auto=update
# Hi\u1ec3n th\u1ecb c\u00e1c c\u00e2u l\u1ec7nh SQL m\u00e0 Hibernate t\u1ef1 \u0111\u1ed9ng sinh ra tr\u00ean Console
spring.jpa.show-sql=true